### PR TITLE
[DCJ-323][risk=no] Lower warning on invalid schemas

### PR DESCRIPTION
**Pull request by rushtong**
### Addresses
https://broadworkbench.atlassian.net/browse/DCJ-323

### Summary
Minor change to lower log level for invalid schemas. These errors do not need to go to Sentry

----
Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

- Label PR with a Jira ticket number and include a link to the ticket
- Label PR with a security risk modifier [no, low, medium, high]
- PR describes scope of changes
- Get a minimum of one thumbs worth of review, preferably two if enough team members are available
- Get PO sign-off for all non-trivial UI or workflow changes
- Verify all tests go green
- Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by fboulnois — APPROVED** [review]
Why is it safe to discard these errors from sentry?

**Comment by rushtong** [comment]
> Why is it safe to discard these errors from sentry?

Because we inform the client that what they provided as input is invalid. Sentry reporting is for actionable errors that we, as developers have to do something for. If a client sends us bad input, there's nothing we can do about that.

**Comment by fboulnois** [comment]
> > Why is it safe to discard these errors from sentry?
> 
> Because we inform the client that what they provided as input is invalid. Sentry reporting is for actionable errors that we, as developers have to do something for. If a client sends us bad input, there's nothing we can do about that.

Are there any situations where it would be valuable to record bad input, e.g. for recording potentially malicious input?

**Comment by rushtong** [comment]
> > > Why is it safe to discard these errors from sentry?
> > 
> > 
> > Because we inform the client that what they provided as input is invalid. Sentry reporting is for actionable errors that we, as developers have to do something for. If a client sends us bad input, there's nothing we can do about that.
> 
> Are there any situations where it would be valuable to record bad input, e.g. for recording potentially malicious input?

We still report the issue, but not in sentry, and instead in GCP logging, so we can still follow up if we want to. There are no data related consequences to malicious input. If there were a security issue related to JSON parsing, I think that would be a separate concern outside the scope of what these endpoints are trying to do.

**Review by aarohinadkarni — APPROVED** [review]
looks good 👍

**Pull request merged**
